@baseUrl = http://localhost:8080
@authToken =
@cart_id =

### LOGIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user1@example.com",
  "password": "123456"
}

> {% client.global.set("authToken", response.body.token); %}

########################################################################
### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "User1",
  "email": "user1@example.com",
  "password": "123456"
}

### GET Current User
GET {{baseUrl}}/auth/me
Authorization: Bearer {{authToken}}

### GET Admin User
GET http://localhost:8080/admin/hello
Authorization: Bearer {{authToken}}

#######################################################################
### Create a Cart
POST {{baseUrl}}/carts
@name cart
Content-Type: application/json
Authorization: Bearer {{authToken}}

> {%
    client.global.set("cart_id", response.body.id);
%}

### Add Items to cart
POST {{baseUrl}}/carts/{{cart_id}}/items
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "productId": 6
}

### Test Checkout
POST {{baseUrl}}/checkout
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "cartId": "{{cart_id}}"
}

### Get All Orders
GET {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Get  Order
GET {{baseUrl}}/orders/1
Content-Type: application/json
Authorization: Bearer {{authToken}}
