### GET all Users
GET http://localhost:8080/users

### GET User by ID
GET http://localhost:8080/users/1

### QueryParameter
GET http://localhost:8080/users?sort=name

### GET all Products
GET http://localhost:8080/products

### GET Product by ID
GET http://localhost:8080/products/4

